version: '3' # version docker compose

services: # services within app
  api-solid-pg: # name of container
    image: bitnami/postgresql # wich image in use?
    ports: 
      - 5432:5432 # ports of container
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apifitfacil